[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  AUTH_USERNAME = "innogy"
  AUTH_PASSWORD = "tahsilat202524ce8688db5a3b4d3e60404d37843c0204a91a3a"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"
    Cache-Control = "no-cache, no-store, must-revalidate"